window.XG_OPERATOR_CATALOG = {
  categories: [
    { id: "control", name: "控制与执行" },
    { id: "estimation", name: "状态估计" },
    { id: "signal", name: "信号与矩阵" },
    { id: "safety", name: "安全与异常检测" },
    { id: "physical", name: "物理仿真" },
  ],
  products: [
    {
      id: "PID",
      name: "PID 控制器",
      sku: "XG-PID-V1",
      category: "control",
      summary: "Q16.16 定点 PID，AXI4-Stream 输入，寄存器可配置。",
      evidence: "PLACED_ROUTED",
      lut: 354,
      ff: 162,
      dsp: 0,
      latency: 6,
      wns: 6.813,
      drc: 0,
      goldenError: 2,
      price: 29800,
    },
    {
      id: "PID_FF",
      name: "PID + 前馈控制器",
      sku: "XG-PID-FF-V1",
      category: "control",
      summary: "PID 与前馈支路并行，适用于已知扰动补偿。",
      evidence: "SYNTHESIZED",
      lut: 549,
      ff: 225,
      dsp: 0,
      latency: 8,
      wns: null,
      drc: null,
      goldenError: 3,
      price: 39800,
    },
    {
      id: "KALMAN",
      name: "SOC 卡尔曼滤波器",
      sku: "XG-KALMAN-V1",
      category: "estimation",
      summary: "三级除法流水线，电流预测，适合电池状态估计。",
      evidence: "PLACED_ROUTED",
      lut: 622,
      ff: 539,
      dsp: 8,
      latency: 14,
      wns: 9.772,
      drc: 0,
      goldenError: 0,
      price: 49800,
    },
    {
      id: "FFT",
      name: "8 点复数 FFT",
      sku: "XG-FFT-V1",
      category: "signal",
      summary: "三级蝶形流水线，QX 定点格式，流接口输出。",
      evidence: "PLACED_ROUTED",
      lut: 3242,
      ff: 1539,
      dsp: 0,
      latency: 18,
      wns: 8.5,
      drc: null,
      goldenError: 2,
      price: 49800,
    },
    {
      id: "CUSUM",
      name: "CUSUM 异常检测",
      sku: "XG-CUSUM-V1",
      category: "safety",
      summary: "单周期累积和检测，适合漂移和突变告警。",
      evidence: "PLACED_ROUTED",
      lut: 210,
      ff: 68,
      dsp: 0,
      latency: 5,
      wns: 8.5,
      drc: 0,
      goldenError: 0,
      price: 19800,
    },
    {
      id: "FARADAY",
      name: "法拉第感应",
      sku: "XG-FARADAY-V1",
      category: "physical",
      summary: "四级流水线，计算感应电动势。",
      evidence: "SYNTHESIZED",
      lut: 599,
      ff: 198,
      dsp: 6,
      latency: 9,
      wns: 8.1,
      drc: null,
      goldenError: 7,
      price: 39800,
    },
    {
      id: "THERMAL",
      name: "热异常预警",
      sku: "XG-THERMAL-V1",
      category: "safety",
      summary: "低资源温升告警，滞回阈值和报警输出。",
      evidence: "PLACED_ROUTED",
      lut: 130,
      ff: 86,
      dsp: 2,
      latency: 4,
      wns: 7.8,
      drc: 0,
      goldenError: 0,
      price: 19800,
    },
    {
      id: "CONV3X3",
      name: "3x3 流式卷积",
      sku: "XG-CONV3X3-V1",
      category: "signal",
      summary: "行缓存与四阶段流水线，适合边缘特征处理。",
      evidence: "PLACED_ROUTED",
      lut: 127,
      ff: 300,
      dsp: 0,
      latency: 8,
      wns: 8.5,
      drc: null,
      goldenError: 7,
      price: 39800,
    },
    {
      id: "SOH_BAYES",
      name: "SOH 贝叶斯估计",
      sku: "XG-SOH-BAYES-V1",
      category: "estimation",
      summary: "离散贝叶斯更新，适合电池健康状态估计。",
      evidence: "SYNTHESIZED",
      lut: 151,
      ff: 132,
      dsp: 8,
      latency: 8,
      wns: 8.5,
      drc: null,
      goldenError: 1,
      price: 39800,
    },
    {
      id: "BORIS",
      name: "Boris 粒子推步",
      sku: "XG-BORIS-V1",
      category: "physical",
      summary: "八级流水线磁场粒子推步，物理仿真加速。",
      evidence: "SYNTHESIZED",
      lut: 367,
      ff: 294,
      dsp: 12,
      latency: 16,
      wns: 5.3,
      drc: null,
      goldenError: 58,
      price: 49800,
    },
  ],
};
